<?php

Yii::import('application.models._base.BaseCubicleSpine');

class CubicleSpine extends BaseCubicleSpine {

	public static function model($className = __CLASS__) {
		return parent::model($className);
	}

	public function attributeLabels() {
		return array(
			'id' => 'ID',
			'name' => 'Name',
			'cubicle_cluster_id' => 'Cubicle Cluster',
			'up1_width' => 'Up1 Width',
			'up2_width' => 'Up2 Width',
			'up3_width' => 'Up3 Width',
			'up4_width' => 'Up4 Width',
			'up5_width' => 'Up5 Width',
			'up6_width' => 'Up6 Width',
			'upward_extend_to_post' => 'Upward Extend To Post',
			'up_f1_e1_id' => 'Up F1 E1',
			'up_f1_e2_id' => 'Up F1 E2',
			'up_f2_e1_id' => 'Up F2 E1',
			'up_f2_e2_id' => 'Up F2 E2',
			'up_f3_e1_id' => 'Up F3 E1',
			'up_f3_e2_id' => 'Up F3 E2',
			'up_f4_e1_id' => 'Up F4 E1',
			'up_f4_e2_id' => 'Up F4 E2',
			'up_f5_e1_id' => 'Up F5 E1',
			'up_f5_e2_id' => 'Up F5 E2',
			'up_f6_e1_id' => 'Up F6 E1',
			'up_f6_e2_id' => 'Up F6 E2',
			'right1_width' => 'Right1 Width',
			'right2_width' => 'Right2 Width',
			'right3_width' => 'Right3 Width',
			'right4_width' => 'Right4 Width',
			'right5_width' => 'Right5 Width',
			'right6_width' => 'Right6 Width',
			'rightward_extend_to_post' => 'Rightward Extend To Post',
			'right_f1_e1_id' => 'Right F1 E1',
			'right_f1_e2_id' => 'Right F1 E2',
			'right_f2_e1_id' => 'Right F2 E1',
			'right_f2_e2_id' => 'Right F2 E2',
			'right_f3_e1_id' => 'Right F3 E1',
			'right_f3_e2_id' => 'Right F3 E2',
			'right_f4_e1_id' => 'Right F4 E1',
			'right_f4_e2_id' => 'Right F4 E2',
			'right_f5_e1_id' => 'Right F5 E1',
			'right_f5_e2_id' => 'Right F5 E2',
			'right_f6_e1_id' => 'Right F6 E1',
			'right_f6_e2_id' => 'Right F6 E2',
			'down_f1_width' => 'Down F1 Width',
			'down_f2_width' => 'Down F2 Width',
			'down_f3_width' => 'Down F3 Width',
			'down_f4_width' => 'Down F4 Width',
			'down_f5_width' => 'Down F5 Width',
			'down_f6_width' => 'Down F6 Width',
			'downward_extend_to_post' => 'Downward Extend To Post',
			'down_f1_e1_id' => 'Down F1 E1',
			'down_f1_e2_id' => 'Down F1 E2',
			'down_f2_e1_id' => 'Down F2 E1',
			'down_f2_e2_id' => 'Down F2 E2',
			'down_f3_e1_id' => 'Down F3 E1',
			'down_f3_e2_id' => 'Down F3 E2',
			'down_f4_e1_id' => 'Down F4 E1',
			'down_f4_e2_id' => 'Down F4 E2',
			'down_f5_e1_id' => 'Down F5 E1',
			'down_f5_e2_id' => 'Down F5 E2',
			'down_f6_e1_id' => 'Down F6 E1',
			'down_f6_e2_id' => 'Down F6 E2',
			'left_f1_width' => 'Left F1 Width',
			'left_f2_width' => 'Left F2 Width',
			'left_f3_width' => 'Left F3 Width',
			'left_f4_width' => 'Left F4 Width',
			'left_f5_width' => 'Left F5 Width',
			'left_f6_width' => 'Left F6 Width',
			'leftward_extend_to_post' => 'Leftward Extend To Post',
			'left_f1_e1_id' => 'Left F1 E1',
			'left_f1_e2_id' => 'Left F1 E2',
			'left_f2_e1_id' => 'Left F2 E1',
			'left_f2_e2_id' => 'Left F2 E2',
			'left_f3_e1_id' => 'Left F3 E1',
			'left_f3_e2_id' => 'Left F3 E2',
			'left_f4_e1_id' => 'Left F4 E1',
			'left_f4_e2_id' => 'Left F4 E2',
			'left_f5_e1_id' => 'Left F5 E1',
			'left_f5_e2_id' => 'Left F5 E2',
			'left_f6_e1_id' => 'Left F6 E1',
			'left_f6_e2_id' => 'Left F6 E2',
			'data' => 'Data',
			'data1' => 'Data1',
		);
	}

}

?>